### ISSUE TITLE
Callback isn't guaranteed to work properly

### ISSUE THREAD

**Issue by dbunna** [paulmillr/async-each#17]
@paulmillr The recent 1.0.4 release introduced a bug (also present in 1.0.5).

Since the count of items processed is no longer counted and the callback is executed when the last item is processed, we can have, and will likely have, a case where the last item finishes being processed before other items, causing the callback to be executed before the other items are finished.

The processed items must be counted in some fashion for this to work correctly.

**Comment by paulmillr** [comment]
Sorry for that. The repo lacked proper tests. 1.0.6 is out.
